### PR TITLE
update sen2like

### PR DESCRIPTION
**Pull request by ValentinaHutter**

### CODE REVIEW

**Comment by LukeWeidenwalker** [comment]
@ValentinaHutter just saw this again, are these new parameters already implemented in the openeo process in the executor? Probably want to merge this close to when we deploy these changes there!

**Comment by ValentinaHutter** [comment]
Yes, would be great to also have the new parameters in the new release… do you plan to do a release today? I can merge my updates to the sen2like implementation and test it tomorrow - would that be okay for you?

**Comment by LukeWeidenwalker** [comment]
No, I don't have a release planned atm, there are no unreleased commits merged in the executor currently! 

> I can merge my updates to the sen2like implementation and test it tomorrow - would that be okay for you?
Sorry, but the order here needs switching: test first, then merge - let me know if you need help with the local testing though!

**Comment by LukeWeidenwalker** [comment]
Sorry, could have been clearer - I think we should do it in the following order:
1) Test & merge https://git.eodc.eu/eodc/eodc-api/faas-sen2like/-/merge_requests/73/diffs. Then release faas-sen2like as a new version to dev
2) Finish implementing the updates to this parametrisation in openeo-executor (in the `sen2like` process locally and I see there's already a PR open (https://git.eodc.eu/eodc/eodc-api/openeo-executor/-/merge_requests/113), where the build fails. Before merging, this wants to be tested locally so that this all works correctly (i.e. parameters are handed over correctly, the job starts correctly and results can be loaded back correctly). 
3) Once 2) is ready to merge, first merge this PR (openeo-processes) and bump the submodule in openeo-processes-dask. Release openeo-processes-dask
4) Bump the version of openeo-processes-dask in the executor and merge the parametrisation updates. release a new version to dev
5) Bump the version of openeo-processes-dask in the API container so the new spec gets picked up and release that to dev

Hope this helps!

**Pull request merged**
