### PR TITLE
DP-266: Add sen2like spec

### PR DESCRIPTION
**Pull request by LukeWeidenwalker**
Closes https://eodc.atlassian.net/browse/DP-266

How do we return the datacube here? One xarray with both L2H and L2F? Or let user toggle which one they want?
We said no other parameters to start, right?

### CODE REVIEW

**Comment by SerRichard** [comment]
I am not sure how it would look in one xarray, if we increase the dimensions by "product", with two values, we are kind of acknowledging these are different things. Though, an openeo process sort of expects one raster-cube output.

In my head, whatever the result of merging two different collections into one raster-cube, is similar to what we might want to return for this? That is kind of what we are doing, right?

**Comment by ValentinaHutter** [comment]
I think it makes sense to let the user pick somehow and set it to L2F per default? For loading it as a result from the previous job, I would expect them to want the L2F, but if someone wants L2H there should be an option for that? :)

**Comment by LukeWeidenwalker** [comment]
> In my head, whatever the result of merging two different collections into one raster-cube, is similar to what we might want to return for this? That is kind of what we are doing, right?

> I think it makes sense to let the user pick somehow and set it to L2F per default? For loading it as a result from the previous job, I would expect them to want the L2F, but if someone wants L2H there should be an option for that? :)

Okay, thanks for that - I guess we could allow any of L2F or L2H or L2F+L2H and just add a dimension `product` in. As long as that's described in the process, it seems valid to me!

**Comment by LukeWeidenwalker** [comment]
@SerRichard @ValentinaHutter added this, please rereview!

**Pull request merged**
